### ISSUE TITLE
请问楼主有没有相关的交流学习群啊？

### ISSUE THREAD

**Issue by johnniev5** [0xMJ/AI-Security-Learning#1]
你好啊，楼主，是学生，还是已经工作了呀？有没有相关的学习交流群可以加入的呀？

**Comment by 0xMJ** [comment]
> 你好啊，楼主，是学生，还是已经工作了呀？有没有相关的学习交流群可以加入的呀？

还是学生，目前能力不足，暂时没有精力做个氛围良好的交流群，后续会考虑，谢谢。
